In [3]:
import os
import pandas as pd

In [2]:
dataset_dir_path = '../../../data/Care_To_Compare/Wind Farm A/Wind Farm A/datasets'
event_file_path = '../../../data/Care_To_Compare/Wind Farm A/Wind Farm A/event_info.csv'

In [90]:
def generate_train_prediction(rows, event_data):
    train_data, prediction_data = {},{}
    for row in rows:
        event_id = event_data.loc[row, 'event_id']
        
        turbine_data = pd.read_csv(dataset_dir_path + '/' + str(event_id) + '.csv', sep = ';')
        
        train_data_piece = turbine_data[turbine_data['train_test'] == 'train']
        prediction_data_piece = turbine_data[turbine_data['train_test'] == 'prediction']
        
        train_data[row] = train_data_piece
        prediction_data[row] = prediction_data_piece
    return train_data, prediction_data

In [87]:
def generate_ground_truth(event_data, prediction_data):
    for row, df in prediction_data.items():
        event_start = event_data.loc[row, 'event_start_id']
        event_end = event_data.loc[row, 'event_end_id']
        if event_data.loc[row, 'event_label'] == 'anomaly':
            df['is_anomaly'] = df['id'].between(event_start, event_end)
        else:
            df['is_anomaly'] = False
        
    return prediction_data

In [91]:
data = pd.read_csv(event_file_path, sep = ';')
rows_used = [4, 0, 12, 15]

In [92]:
train, prediction = generate_train_prediction(rows_used, data)

In [93]:
prediction.keys()

dict_keys([4, 0, 12, 15])

In [94]:
prediction = generate_ground_truth(data, prediction)

In [97]:
prediction[4]

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg,is_anomaly
52220,2023-09-03 00:50:00,11,52220,prediction,0,25.0,103.4,2.4,10.8,10.3,...,-30048.0,0.0,283568.0,-30048.0,14.9,15.2,14.5,0.1,26.0,False
52221,2023-09-03 01:00:00,11,52221,prediction,0,25.0,102.8,1.8,10.1,9.7,...,-29868.0,0.0,247683.0,-29868.0,14.8,15.1,13.8,0.2,26.0,False
52222,2023-09-03 01:10:00,11,52222,prediction,0,25.0,104.7,3.6,10.4,9.9,...,-29460.0,0.0,263128.0,-29460.0,14.9,15.1,14.6,0.1,26.0,False
52223,2023-09-03 01:20:00,11,52223,prediction,0,25.0,103.7,2.6,10.1,9.6,...,-30105.0,0.0,246197.0,-30105.0,14.9,15.2,14.7,0.1,26.0,False
52224,2023-09-03 01:30:00,11,52224,prediction,0,25.0,106.3,5.2,9.9,9.5,...,-29105.0,0.0,235898.0,-29105.0,14.9,15.2,14.6,0.1,26.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54808,2023-09-21 00:10:00,11,54808,prediction,0,23.0,100.6,-2.5,5.5,5.3,...,-16430.0,0.0,36975.0,-16430.0,11.3,12.1,10.9,0.2,23.0,False
54809,2023-09-21 00:20:00,11,54809,prediction,0,23.0,104.1,0.9,6.4,6.2,...,-18831.0,0.0,63707.0,-18831.0,12.2,14.1,11.0,0.8,23.0,False
54810,2023-09-21 00:30:00,11,54810,prediction,0,22.0,104.4,1.2,6.5,6.4,...,-22722.0,0.0,72413.0,-22722.0,12.3,14.4,11.1,0.7,23.0,False
54811,2023-09-21 00:40:00,11,54811,prediction,0,22.0,103.0,-0.2,6.9,6.7,...,-23677.0,0.0,82863.0,-23677.0,13.1,14.7,10.9,1.0,23.0,False
54812,2023-09-21 00:50:00,11,54812,prediction,0,22.0,102.0,-1.1,6.1,5.9,...,-21128.0,0.0,56495.0,-21128.0,12.0,14.6,10.8,1.0,23.0,False

In [98]:
((prediction[4]).loc[prediction[4]['is_anomaly'] == True])

Empty DataFrame
Columns: [time_stamp, asset_id, id, train_test, status_type_id, sensor_0_avg, sensor_1_avg, sensor_2_avg, wind_speed_3_avg, wind_speed_4_avg, wind_speed_3_max, wind_speed_3_min, wind_speed_3_std, sensor_5_avg, sensor_5_max, sensor_5_min, sensor_5_std, sensor_6_avg, sensor_7_avg, sensor_8_avg, sensor_9_avg, sensor_10_avg, sensor_11_avg, sensor_12_avg, sensor_13_avg, sensor_14_avg, sensor_15_avg, sensor_16_avg, sensor_17_avg, sensor_18_avg, sensor_18_max, sensor_18_min, sensor_18_std, sensor_19_avg, sensor_20_avg, sensor_21_avg, sensor_22_avg, sensor_23_avg, sensor_24_avg, sensor_25_avg, sensor_26_avg, reactive_power_27_avg, reactive_power_27_max, reactive_power_27_min, reactive_power_27_std, reactive_power_28_avg, reactive_power_28_max, reactive_power_28_min, reactive_power_28_std, power_29_avg, power_29_max, power_29_min, power_29_std, power_30_avg, power_30_max, power_30_min, power_30_std, sensor_31_avg, sensor_31_max, sensor_31_min, sensor_31_std, sensor_32_avg, sensor_33_avg, sensor_34_avg, sensor_35_avg, sensor_36_avg, sensor_37_avg, sensor_38_avg, sensor_39_avg, sensor_40_avg, sensor_41_avg, sensor_42_avg, sensor_43_avg, sensor_44, sensor_45, sensor_46, sensor_47, sensor_48, sensor_49, sensor_50, sensor_51, sensor_52_avg, sensor_52_max, sensor_52_min, sensor_52_std, sensor_53_avg, is_anomaly]
Index: []

[0 rows x 87 columns]